nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= v2.9.3"
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0"
